// Auth
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Edit panel - country list
export const ADD_NEW_COUNTRY = 'ADD_NEW_COUNTRY';
export const REMOVE_COUNTRY = 'REMOVE_COUNTRY';
export const GET_DB_COUNTRIES = 'GET_DB_COUNTRIES';
export const ADD_NEW_FOODGROUP = 'ADD_NEW_FOODGROUP';
export const REMOVE_FOODGROUP = 'REMOVE_FOODGROUP';
export const GET_DB_FOODGROUPES = 'GET_DB_FOODGROUPES';

// Vendor reg form
export const FETCH_IN_VENREG = 'FETCH_IN_VENREG';
export const INPUT_CHANGE_IN_VENREG = 'INPUT_CHANGE_IN_VENREG';
export const MARKED_INPUT_CHANGE_IN_VENREG = 'MARKED_INPUT_CHANGE_IN_VENREG';
export const MULTI_SELECT_CHANGE_IN_VENREG = 'MULTI_SELECT_CHANGE_IN_VENREG';
export const CREATE_UNIT_IN_VENREG = 'CREATE_UNIT_IN_VENREG';
export const REMOVE_UNIT_FROM_VENREG = 'REMOVE_UNIT_FROM_VENREG';

// Scratch card transaction form
export const FETCH_IN_TRANSACTION = 'FETCH_IN_TRANSACTION';
export const INPUT_CHANGE_IN_TRANSACTION = 'INPUT_CHANGE_IN_TRANSACTION';
export const FETCH_VENDOR_DATA_IN_TRANSACTION = 'FETCH_VENDOR_DATA_IN_TRANSACTION';
export const SET_TOTAL_COST_IN_TRANSACTION = 'SET_TOTAL_COST_IN_TRANSACTION';

// Record call form
export const FETCH_IN_HOTLINE = 'FETCH_IN_HOTLINE';
export const INPUT_CHANGE_IN_HOTLINE = 'INPUT_CHANGE_IN_HOTLINE';


