export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_NEW_COUNTRY = 'ADD_NEW_COUNTRY';
export const REMOVE_COUNTRY = 'REMOVE_COUNTRY';
export const GET_DB_COUNTRIES = 'GET_DB_COUNTRIES';

// Vendor reg form
export const FETCH_IN_VENREG = 'FETCH_IN_VENREG';
export const INPUT_CHANGE_IN_VENREG = 'INPUT_CHANGE_IN_VENREG';
export const MARKED_INPUT_CHANGE_IN_VENREG = 'MARKED_INPUT_CHANGE_IN_VENREG';
export const MULTI_SELECT_CHANGE_IN_VENREG = 'MULTI_SELECT_CHANGE_IN_VENREG';
export const CREATE_UNIT_IN_VENREG = 'CREATE_UNIT_IN_VENREG';
export const REMOVE_UNIT_FROM_VENREG = 'REMOVE_UNIT_FROM_VENREG';
