// Auth
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Admin-panel 
export const ADD_NEW_COUNTRY = 'ADD_NEW_COUNTRY';
export const REMOVE_COUNTRY = 'REMOVE_COUNTRY';
export const GET_DB_COUNTRIES = 'GET_DB_COUNTRIES';
export const ADD_NEW_FOODGROUP = 'ADD_NEW_FOODGROUP';
export const REMOVE_FOODGROUP = 'REMOVE_FOODGROUP';
export const GET_DB_FOODGROUPES = 'GET_DB_FOODGROUPES';
export const ADD_NEW_ORG = 'ADD_NEW_ORG';
export const REMOVE_ORG = 'REMOVE_ORG';
export const GET_DB_ORGS = 'GET_DB_ORGS';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const GET_DB_QUESTIONS = 'GET_DB_QUESTIONS';

// Vendor reg form
export const FETCH_IN_VENREG = 'FETCH_IN_VENREG';
export const FETCH_COUNTRY_IN_VENREG = 'FETCH_COUNTRY_IN_VENREG';
export const INPUT_CHANGE_IN_VENREG = 'INPUT_CHANGE_IN_VENREG';
export const MARKED_INPUT_CHANGE_IN_VENREG = 'MARKED_INPUT_CHANGE_IN_VENREG';
export const MULTI_SELECT_CHANGE_IN_VENREG = 'MULTI_SELECT_CHANGE_IN_VENREG';
export const CREATE_UNIT_IN_VENREG = 'CREATE_UNIT_IN_VENREG';
export const REMOVE_UNIT_FROM_VENREG = 'REMOVE_UNIT_FROM_VENREG';
export const GET_DB_VENDORS = 'GET_DB_VENDORS';
export const SET_SINGLE_MAP_MARK_COORDINATES = 'SET_SINGLE_MAP_MARK_COORDINATES'

// Scratch card transaction form
export const FETCH_IN_TRANSACTION = 'FETCH_IN_TRANSACTION';
export const INPUT_CHANGE_IN_TRANSACTION = 'INPUT_CHANGE_IN_TRANSACTION';
export const FETCH_VENDOR_DATA_IN_TRANSACTION = 'FETCH_VENDOR_DATA_IN_TRANSACTION';
export const SET_TOTAL_COST_IN_TRANSACTION = 'SET_TOTAL_COST_IN_TRANSACTION';

// Record call form
export const FETCH_IN_HOTLINE = 'FETCH_IN_HOTLINE';
export const INPUT_CHANGE_IN_HOTLINE = 'INPUT_CHANGE_IN_HOTLINE';

// SortBar
export const SORT_BY_ALL_VENDORS = 'SORT_BY_ALL_VENDORS'
export const SORT_BY_COUNTRIES_VENDORS = 'SORT_BY_COUNTRIES_VENDORS'
export const SORT_BY_CITIES_VENDORS = 'SORT_BY_CITIES_VENDORS'
export const SORT_BY_ISOPEN_VENDORS = 'SORT_BY_ISOPEN_VENDORS'
export const SORT_BY_FOODGROUP_VENDORS = 'SORT_BY_FOODGROUP_VENDORS'
export const SORT_BY_OSS_VENDORS = 'SORT_BY_OSS_VENDORS'
export const SORT_BY_FLAG_VENDORS = 'SORT_BY_FLAG_VENDORS'
export const SORT_BY_STARS_VENDORS = 'SORT_BY_STARS_VENDORS'
export const SORT_BY_COUNTRIES_VENDORS_MAP = 'SORT_BY_COUNTRIES_VENDORS_MAP'
export const SORT_BY_CITIES_VENDORS_MAP = 'SORT_BY_CITIES_VENDORS_MAP'

// User profile
export const HANDLE_INPUT_CHANGE_IN_USER_PROFILE_EDIT = 'HANDLE_INPUT_CHANGE_IN_USER_PROFILE_EDIT'

// Inspection 
export const FETCH_IN_INSPECTION = 'FETCH_IN_INSPECTION'
export const SET_TOTAL_OSS_IN_INSPECTION = 'SET_TOTAL_OSS_IN_INSPECTION'

// Report
export const FETCH_IN_REPORT = 'FETCH_IN_REPORT'
export const INPUT_CHANGE_IN_REPORT = 'INPUT_CHANGE_IN_REPORT'
export const MULTI_SELECT_IN_REPORT = 'MULTI_SELECT_IN_REPORT'
export const REPORT_CHECKBOX_HANDLING = 'REPORT_CHECKBOX_HANDLING'
// Report donwload
export const PREPARE_DONWLOAD_DATA = 'PREPARE_DONWLOAD_DATA'

// Confirm registration at admin panel
export const FETCH_IN_CONFIRM = 'FETCH_IN_CONFIRM'




